config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resources :reviews
  end
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :reviews

    has_attached_file :book_img, styles: { :book_index=> "250x300>",:book_show=> "300x300>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :find_book , only: [:show,:edit,:destroy,:update]
    before_action :authenticate_user!,only:[:new,:edit]
    def index
        if params[:category].blank?
            @books=Book.all.order("created_at DESC")
        else
            @category_id=Category.find_by(:name=>params[:category]).id
            @books=Book.where(:category_id=>@category_id).order("created_at DESC")
        end
        
    end

    def show
        if @book.reviews.blank?
            @average_review=0
        else
            @average_review=@book.reviews.average(:raiting).round(2)
        end
    end



    def new
        @book=current_user.books.build
        @categories=Category.all.map{ |c| [c.name,c.id]}
    end

    def create
        @book=current_user.books.build(book_params)
        @book.category_id=params[:category_id]
        if @book.save
            redirect_to root_path
        else
            render "new"
        end
    end

    def edit
        @categories=Category.all.map{ |c| [c.name,c.id]}
    end

    def update
        @book.category_id=params[:category_id]
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            render "edit"
        end
    end

    def destroy
        @book.destroy
        redirect_to root_path
    end

    private

    def book_params
        params.require(:book).permit(:title,:description,:author,:category_id,:book_img)
    end

    def find_book
        @book=Book.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_book
    before_action :find_review, only:[:edit,:update,:destroy]
    before_action :authenticate_user!,only:[:new,:edit]

    def new
        @review=Review.new
    end

    def create
        @review=Review.new(review_params)
        @review.book_id=@book.id
        @review.user_id=current_user.id
        if @review.save
            redirect_to book_path(@book)
        else 
            render 'new'
        end
    end

    def edit 
    end


    def update
        if @review.update(review_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end

    def destroy
        @review.destroy
        redirect_to book_path(@book)
    end


    private

    def review_params
        params.require(:review).permit(:raiting,:comment)
    end

    def find_book
        @book=Book.find(params[:book_id])
    end
    
    def find_review
        @review=Review.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
    <%= select_tag(:category_id,options_for_select(@categories),:prompt=>"Select and category",class:"form-control") %>
    <%= f.file_field :book_img %>
    <%= f.input :title ,label: "Title",class:"form-control"%>
    <%= f.input :description ,class:"form-control"%>
    <%= f.input :author ,class:"form-control"%>
    <%= f.button :submit ,class:"btn-primary"%>
<% end %>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
    <div class="panel-heading"><h2>Edit Book</h2></div>
    <div class="panel-body">
       <%= simple_form_for @book,:html=>{:multipart=>true} do |f| %>
            <%= f.select :category_id, @categories %>
            <%= f.file_field :book_img %>
            <%= f.input :title ,label: "Title",class:"form-control"%>
            <%= f.input :description ,class:"form-control"%>
            <%= f.input :author ,class:"form-control"%>
            <%= f.button :submit ,class:"btn-primary"%>
        <% end %>
   
    </div>
      <div class="panel-footer"> <%= link_to "back" ,root_path ,class:"btn btn-info"%></div>
    </div>
</div>

app/views/books/index.html.erb
<div class="clearfix"></div>
<h4>List Books</h4>
<h5><%=params[:category]%></h5>
<% if @books.count== 0 %>
        <div class="alert alert-dismissible alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h6>There are no books currently in this category.</h6>
    </div>
<% else %>
        <div class="row">
            <% @books.each do |book| %>
                <div class="col-md-4">
                <div class="panel panel-default" style="width:233px;">
                <div class="panel-body">
                     <a href="/books/<%= book.id%>">
                        <%= image_tag book.book_img.url(:book_index) %>
                    </a>
                </div>
                </div>
                  
                </div>
            <% end %>
        </div>
<% end %>

<%= link_to "New book",new_book_path ,class:"btn btn-success" %>

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
    <div class="panel-heading"><h2>New Book</h2></div>
    <div class="panel-body">
        <%= render "form" %>
   
    </div>
      <div class="panel-footer"> <%= link_to "back" ,root_path ,class:"btn btn-info"%></div>
    </div>
</div>

app/views/books/show.html.erb
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-body text-center">
                <%= image_tag @book.book_img.url(:book_show) %>
                
            </div>
        </div>
        
    </div>
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-body">
                <h2><%=@book.title%></h2>
                <h4><%=@book.author%></h4>
                <h5>Average raiting</h5>
                <div class="average-review-raiting" data-score="<%= @average_review %>"> </div>
                <span>Based on <%= @book.reviews.count %> reviews  </span>
                <h4><%= @book.category.name %></h4>
                <p><%=@book.description%></p>
            </div>
        </div>
   
    </div>
</div>
<div class="row">
    <div class="col-md-4">
    <!--Where can put reviews-->
     <% if current_user.id == @book.user_id %>
        <div class="panel panel-default text-center">
            <div class="panel-body">
            
                        <%= link_to 'Edit' ,edit_book_path(@book) ,class:"btn btn-warning btn-block"%>
                        <%= link_to "Delete" ,book_path(@book) ,method: :delete,data:{confirm: "Are you sure ?"},class:"btn btn-danger btn-block"%>
            
            </div>
        </div>
     <% end %>
    <div class="list-group">
        <%= render @book.reviews %>
    </div>
    
        <div>
            <%= link_to 'add review', new_book_review_path(@book) ,class:"btn btn-info btn-block"%>
            <%= link_to "back" ,root_path ,class: "btn btn-primary btn-block"%>
        </div>
    </div>
</div>



<script>
    $(".review-raiting").raty({
        readOnly:true,
        score:function(){
            return $(this).attr("data-score");
        },
        path:"/assets/"
    })

    
        $(".average-review-raiting").raty({
        readOnly:true,
        score:function(){
            return $(this).attr("data-score");
        },
        path:"/assets/"
    })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookRev</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'BookRev', root_path,class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if !user_signed_in? %>
            <li>
              <%= link_to 'Sign Up', new_user_registration_path %>
            </li>

              <li>
              <%= link_to 'Log In', new_user_session_path %>
            </li>
            <% end %>
          </ul>
      
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
              <% Category.all.each do |c| %>
                <li class=<%= "active" if params[:category]==c.name %>><%= link_to c.name, books_path(category: c.name) ,class: "link"%></li>
              <% end %>
              </ul>
            </li>
            <li><%= link_to 'Add new Book', new_book_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path,"method": :delete %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="col-md-6 col-md-offset-3">
        <% if notice %>
          <p class="alert alert-dismissible alert-info"><%= notice %></p>
        <% elsif alert %>
          <p class="alert alert-dismissible alert-warning"><%= alert %></p>
        <% end %>
      </div>
      <%= yield %>
    </div>
   
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@book,@book.reviews.build]) do |f| %>
    <div id="raiting-form">
        <label> Raiting</label>
    </div>
    
    <%= f.input :comment ,class:'form-control'%>
    <%= f.button :submit ,class:'btn btn-primary'%>

<% end %>

<script>
    $("#raiting-form").raty({
        path: "/assets/",
        scoreName:"review[raiting]"
    });
</script>

app/views/reviews/_review.html.erb
  <div href="#" class="list-group-item">
    
    <p class="list-group-item-text">
        <div class="review-raiting" data-score="<%= review.raiting %>"></div>
        <h5>Comment: <%= review.comment %> </h5>
        <% if user_signed_in? %>
            <% if review.user_id == current_user.id %>
                <%= link_to 'Edit', edit_book_review_path(review.book,review) ,class:"btn btn-warning"%>
                <%= link_to 'Delete', book_review_path(review.book,review),class:"btn btn-danger",method: :delete,data:{confirm: "Are you sure ?"}%>
            <% end %>
        <% end %>
    </p>

  </div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
    <div class="panel-heading"><h3>Edit review</h3></div>
    <div class="panel-body">
        <%= simple_form_for([@book,@review]) do |f| %>
            <div id="raiting-form">
                <label> Raiting</label>
            </div>
            <%= f.input :comment ,class:'form-control'%>
            <%= f.button :submit ,class:'btn btn-primary'%>

        <% end %>
    </div>
    </div>
</div>

<script>
    $("#raiting-form").raty({
        path: "/assets/",
        scoreName:"review[raiting]",
        score:"<%= @review.raiting %>"
    });
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
    <div class="panel-heading"><h3>New Review</h3></div>
    <div class="panel-body">
        <%= render 'form' %>
    </div>
    </div>
</div>